# Generated by Django 2.2.6 on 2019-12-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191202_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='year',
            new_name='Semester',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
    ]
