# Generated by Django 2.2.6 on 2019-12-25 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191225_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignsubtosem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Semester')),
                ('course_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Course')),
            ],
            options={
                'db_table': 'Assignsemester',
            },
        ),
    ]
