# Generated by Django 2.2.6 on 2020-04-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191210_1504'),
        ('users', '0004_assignsubtosem'),
    ]

    operations = [
    ]
